### PR TITLE
Fix `Command failed with status 127` (#162)

### PR DESCRIPTION
**Pull request by NicolasCombe5555**
Same issue -> #172 
Sorry again, not sure why when I test it against my fork it works but when we released `0.29.1` it was not. Anyway I believe 🙏🏻 this will fix it.

### CODE REVIEW

**Review by ashfurrow — APPROVED** [review]
Makes sense 👍 Ruby is weird, and it's weirdest when it runs on CI.

**Comment by ashfurrow** [comment]
I've released this as 0.29.2, whenever you have a chance to test 👍

**Comment by NicolasCombe5555** [comment]
So still an error but this is weird, when running `bundle update danger-swiftlint`

**Comment by ashfurrow** [comment]
Wow! Weird, I don't see it in the generated `.gem` file either.

OH okay I see the problem. The download script is a `.sh` file, but only `.rb` files are included in the gemspec. That would explain why it works locally. I'll push a change now to fix 👍

**Comment by ashfurrow** [comment]
That should be fixed here:

https://github.com/ashfurrow/danger-ruby-swiftlint/commit/0b9223cb2eef48beead03784d0e655e2288bc9e4#diff-c0aa4fa469ac733041252c4ce300c3dbddcbd911efac82f5e0198efd2231e5e1R17

That was released in 0.29.3. Sorry for all the turnaround here!

**Comment by NicolasCombe5555** [comment]
It works now 🎉

**Comment by ashfurrow** [comment]
Yay! Thanks for verifying 👍

**Pull request merged**
