### PR TITLE
Updated thor to latest version

### PR DESCRIPTION
**Pull request by bradphilips**
This will update thor to the latest stable versions ~> 1.0.0.

### CODE REVIEW

**Review by jason-easterday — APPROVED** [review]
Looks good, glad to see staying current on versions

**Comment by sphanley** [comment]
@ashfurrow any possibility of getting this dependency update into a future release? The currently used version of Thor flags as having security vulnerabilities.

**Review by ashfurrow — APPROVED** [review]
Hello! These changes look great, thanks for taking the time to do this 🙇‍♂️ 

Apologies for the delay response, I think this got lost in shuffle during a busy time at work. 

@sphanley appropriate nudge to an open source maintainer, you set a great example. Thanks for putting this back on my radar.

**Comment by ashfurrow** [comment]
This change is released in 0.35.0, thanks again 👍

**Comment by sphanley** [comment]
Thanks so much, @ashfurrow! We're very appreciative of your work on this project!

**Pull request merged**
