### PR TITLE
Update swiftlint version from 0.26 to 0.27

### PR DESCRIPTION
**Pull request by rafalszastok**
Update swiftlint version

### CODE REVIEW

**Comment by rafalszastok** [comment]
Thanks, @thii can you add tag for 0.17.4?

**Comment by thii** [comment]
@rafalszastok I just added a tag for 0.17.4, but I can't release to Ruby Gems. You can point your Gemfile to this repo to get the update.

**Comment by ashfurrow** [comment]
@thii Thanks! I've added you as an owner to the RubyGem, would you like to trying pushing a release?

**Comment by thii** [comment]
@ashfurrow Thanks! I'll give it a try. Btw, can you also fix the typo in the description of this repo? SwifLlint -> SwiftLint.

**Comment by thii** [comment]
0.17.4 was released to RubyGems. Thanks again everyone!

**Comment by ashfurrow** [comment]
@thii ha, whoops 😛 Fixed now. Thanks for the release!

**Pull request merged**
