### PR TITLE
Remove unary plus operator from message string.

### LINKED ISSUE #119: [Question] Undefined method for Swiflint four issues - during Jenkins Build
Hello, first of all, I'd like to thank the maintainer of this repository for writing this tool!

I am encountering this error during Swiftlint phase on my Jenkins Pipeline job and I cannot determine what could be the problem. Same Dangerfile worked really smooth in another project with same gems, dependencies but with another CI (Travis).

```
+ bundle exec danger
/Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-swiftlint-0.12.1/lib/danger_plugin.rb:106:in `lint_files': [31m (Danger::DSLError)
[!] Invalid `Dangerfile` file: undefined method `+@' for "### SwiftLint found issues\n\n":String[0m
 #  from Dangerfile:42
 #  -------------------------------------------
 #  swiftlint.directory = app_path
 >  swiftlint.lint_files(app_files, inline_mode: false)
 #  
 #  -------------------------------------------
	from Dangerfile:42:in `eval_file'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:297:in `eval'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:297:in `eval_file'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:197:in `parse'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:273:in `run'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/executor.rb:28:in `run'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/commands/runner.rb:70:in `run'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/bin/danger:5:in `<top (required)>'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/bin/danger:23:in `load'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/bin/danger:23:in `<main>'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[!] The exception involves the following plugins:
 -  danger-swiftlint
```

My Swiftlint related lines are as follows in *Dangerfile*

```
app_path = File.join(BASE_PATH, APP_DIR)
test_path = File.join(BASE_PATH, TESTS_DIR)
files = (git.added_files + git.modified_files).map { |path| File.join(BASE_PATH, path) }
app_files = files.select { |path| path.start_with?(app_path + '/') }
test_files = files.select { |path| path.start_with?(test_path + '/') }

swiftlint.directory = app_path
swiftlint.lint_files(app_files, inline_mode: false)

swiftlint.directory = test_path
swiftlint.lint_files(test_files, inline_mode: false)
```

EDIT:
When I enter on my Jenkins Mac Mini and run `danger pr` it works, but it does not show half of the reports. Looks like it reports only Swiftlint for `app_path`. Still, Jenkins fails whole Danger process.

If You have any questions, please ask, I will answer them when possible. Suggestions welcome! Thank you again!
Michael.

### PR DESCRIPTION
**Pull request by Drwalcore**
#trivial resolves #119

### CODE REVIEW

**Comment by ashfurrow** [comment]
Ah, I know what the CI failure is. Hold on...

**Comment by Drwalcore** [comment]
I hope my change was not so bad to fail 18 test cases.

**Comment by ashfurrow** [comment]
Hmm okay, so it looks like the unary `+` operator was [added in Ruby 2.3.0 to "unfreeze" strings](http://ruby-doc.org/core-2.3.0/String.html#method-i-2B-40), which was added for a whole "frozen string literals" thing. It's kinda complicated, but I think I can get it to work with newer and older Ruby versions...

**Comment by ashfurrow** [comment]
@Drwalcore that's a good question without a simple answer. Ruby doesn't have a compiler so we rely on unit tests to provide confidence in the code that a compiler would normally provide. On the other hand, Ruby doesn't have the Swift-style "if this version of Swift else if this version" kind of syntax. (Well, it might have it but I don't use it.) 

A more robust CI suite would run the tests against multiple "officially supported" Ruby versions, which is kind of overkill for this project imo. Switching from unary `+` to `.dup` (for "duplicate") is a pretty small change to keep support for older Ruby versions, so let's do that 👍

**Comment by ashfurrow** [comment]
Okay, I've released version 0.18.1 with this change. You should be able to `bundle update danger-swiftlint` to get the changes.

**Pull request merged**
