### PR TITLE
feat: swiftlint 0.50.3 update

### PR DESCRIPTION
**Pull request by FabienLydoire**

### CODE REVIEW

**Review by mokagio — APPROVED** [review]
I run `bundle exec rake swiftlint:install` locally and it succeeded. `ext/swiftlint/bin/swiftlint version` was 0.50.3, as expected. To me, that validates these changes.

Thank you @FabienLydoire

**Comment by FabienLydoire** [comment]
Thank you for accepting my PR #192 
Now, can anyone release Danger with this update please ?

**Comment by ashfurrow** [comment]
That's been released as version `0.32.0` 👍

**Comment by FabienLydoire** [comment]
Great ! Thank you Ash 🥇

**Pull request merged**
