### PR TITLE
feat: swiftlint version update for inclusive_language allowance list support

### PR DESCRIPTION
**Pull request by apps4everyone**
swiftlint version update for inclusive_language allowance list support

https://github.com/ashfurrow/danger-ruby-swiftlint/issues/165

### CODE REVIEW

**Comment by apps4everyone** [comment]
opened the PR @mokagio @ashfurrow 
let me know if there is something missing...

**Review by mokagio — APPROVED** [review]
LGTM.

I checked out this branch and run `bundle exec rake swiftlint:install` from `ext/swiftlint`, which  completed successfully.

**Review by ashfurrow — APPROVED** [review]
Thank you! I'll get this merged and released today.

**Comment by ashfurrow** [comment]
Okay! This change has been released in [version 0.27.0](https://github.com/ashfurrow/danger-ruby-swiftlint/releases/tag/0.27.0) to RubyGems. Thanks again!

**Comment by apps4everyone** [comment]
Thank you!

**Comment by apps4everyone** [comment]
already tested and 0.27.0 is fixing our problems, thx

**Pull request merged**
